# Generated by Django 4.2.28 on 2026-02-07 20:41

import affiliates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پورسیون')),
                ('source_transaction_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ تراکنش مبدا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.referral')),
            ],
            options={
                'verbose_name': 'پورسیون',
                'verbose_name_plural': 'پورسیون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(default=affiliates.models.generate_referral_code, max_length=20, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='درصد پورسیون (مثلا 0.05 = 5%)', max_digits=5, verbose_name='نرخ پورسیون')),
                ('is_active', models.BooleanField(default=True)),
                ('total_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مجموع درآمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل افیلیت',
                'verbose_name_plural': 'پروفایل\u200cهای افیلیت',
            },
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(check=models.Q(('referrer', models.F('referred')), _negated=True), name='no_self_referral'),
        ),
    ]
