# Generated by Django 4.2.28 on 2026-02-07 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=20, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('initiated', 'آغاز شده'), ('redirected', 'هدایت شده'), ('verified', 'تایید شده'), ('failed', 'ناموفق')], default='initiated', max_length=20)),
                ('description', models.TextField(blank=True, default='شارژ کیف پول')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رکورد پرداخت',
                'verbose_name_plural': 'رکوردهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
